### PR TITLE
Adding audit fields for time taken to run individual tests

### PR DESCRIPTION
**Pull request by jamessimone**
I'm using dmc to run cli unit tests and these audit fields were helpful to include in the tooling response!

### CODE REVIEW

**Comment by jamessimone** [comment]
@jeffdonthemic Jeff have you had a chance to take a look at this?  It's a hopefully very minor change but it would help a lot for some projects that have nforce-tooling dependencies.  Thanks!

**Comment by mikegedelman** [comment]
This repository isn't maintained any more, I have had a PR open for over a year...

Time for a fork I think

**Comment by mikegedelman** [comment]
I've switched most of my stuff to [jsforce](https://github.com/jsforce/jsforce) which is actually maintained

**Comment by jamessimone** [comment]
@mikegedelman thanks - I had noticed yours hadn't received a response yet either.  Oh well.

**Comment by kevinohara80** [comment]
@mikegedelman @jamessimone I just reached out to Jeff to see if there is a better way to manage this repo. Rest assured, we'll get it back on track.

**Review by kevinohara80 — APPROVED** [review]
LGTM

**Comment by kevinohara80** [comment]
@jeffdonthemic this one also looks good to merge

**Pull request merged**
